# Generated by Django 2.1.3 on 2019-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20181203_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='average_review_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='sum_review_score',
            field=models.FloatField(default=0),
        ),
    ]
