# Generated by Django 2.1.5 on 2019-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20191209_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='average_review_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='sum_review_score',
            field=models.FloatField(default=0),
        ),
    ]
